# Generated by Django 2.2.8 on 2022-03-11 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0002_node_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='month',
            field=models.CharField(default='', max_length=2),
            preserve_default=False,
        ),
    ]
