# Generated by Django 2.2.8 on 2022-03-11 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0004_auto_20220310_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='color',
            field=models.CharField(default='aliceblue', max_length=20),
        ),
    ]
